name: guerrero_barber_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_storage: ^12.0.0
  table_calendar: ^3.0.0
  dynamic_background: ^0.5.0
  curved_navigation_bar: ^1.0.6
  flutter_localization: ^0.3.2
  google_sign_in: ^6.3.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  android_alarm_manager_plus: ^4.0.7
  timeline_tile: ^2.0.0
  image_picker: ^1.0.7
  supabase_flutter: ^2.3.4
  app_links: ^6.4.0
  firebase_messaging: ^15.2.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  jwt_decoder: ^2.0.1
  jose: ^0.3.4
  crypto: ^3.0.3
  basic_utils: ^5.7.0
  url_launcher: ^6.3.1
  flutter_map: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env