name: guerrero_barber_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  table_calendar: ^3.0.0
  dynamic_background: ^0.5.0
  curved_navigation_bar: ^1.0.6
  flutter_localization: ^0.3.2
  google_sign_in: ^6.3.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
