// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlk3y6tkC3EETtP49k6Rwva7FYkqkFX_0',
    appId: '1:1007565822434:web:05695ba4aa7a9f7b4541bb',
    messagingSenderId: '1007565822434',
    projectId: 'guerrerobarberapp',
    authDomain: 'guerrerobarberapp.firebaseapp.com',
    storageBucket: 'guerrerobarberapp.firebasestorage.app',
    measurementId: 'G-W95NKBSG07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgYIPD74JV1ajP9fL7Wa1QtP8w9Tfm1f4',
    appId: '1:1007565822434:android:b6f70546f3a272764541bb',
    messagingSenderId: '1007565822434',
    projectId: 'guerrerobarberapp',
    storageBucket: 'guerrerobarberapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WQsmHmqEJLT7r_LLh0L_qdT8dZs2jS8',
    appId: '1:1007565822434:ios:fdac4987184db8294541bb',
    messagingSenderId: '1007565822434',
    projectId: 'guerrerobarberapp',
    storageBucket: 'guerrerobarberapp.firebasestorage.app',
    androidClientId:
        '1007565822434-kq915ritsl6lh1ufl74acdmramkgag30.apps.googleusercontent.com',
    iosClientId:
        '1007565822434-ti25s7cfplaqu6vpmml8ts1hinubjdq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.guerreroBarberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_WQsmHmqEJLT7r_LLh0L_qdT8dZs2jS8',
    appId: '1:1007565822434:ios:fdac4987184db8294541bb',
    messagingSenderId: '1007565822434',
    projectId: 'guerrerobarberapp',
    storageBucket: 'guerrerobarberapp.firebasestorage.app',
    androidClientId:
        '1007565822434-kq915ritsl6lh1ufl74acdmramkgag30.apps.googleusercontent.com',
    iosClientId:
        '1007565822434-ti25s7cfplaqu6vpmml8ts1hinubjdq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.guerreroBarberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlk3y6tkC3EETtP49k6Rwva7FYkqkFX_0',
    appId: '1:1007565822434:web:4f2dcfa21ae638644541bb',
    messagingSenderId: '1007565822434',
    projectId: 'guerrerobarberapp',
    authDomain: 'guerrerobarberapp.firebaseapp.com',
    storageBucket: 'guerrerobarberapp.firebasestorage.app',
    measurementId: 'G-LSTHK4F2H6',
  );
}
